version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: drawai-postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5433:5432'
        volumes:
            - drawai-postgres:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    drawai-postgres:
